INSERT INTO peliculas (id, nombre, genero, estreno, idioma) VALUES (1, 'El Padrino', 'Crimen, Drama', 1972, 'Ingles');
INSERT INTO peliculas (id, nombre, genero, estreno, idioma) VALUES (2, 'El Senior de los Anillos: La Comunidad del Anillo', 'Aventura, Fantasia', 2001, 'Ingles');
INSERT INTO peliculas (id, nombre, genero, estreno, idioma) VALUES (3, 'Pulp Fiction', 'Crimen, Drama', 1994, 'Ingles');
INSERT INTO peliculas (id, nombre, genero, estreno, idioma) VALUES (4, 'La Guerra de las Galaxias', 'Aventura, Fantasia', 1977, 'Ingles');
INSERT INTO peliculas (id, nombre, genero, estreno, idioma) VALUES (5, 'Titanic', 'Drama, Romance', 1997, 'Ingles');
INSERT INTO peliculas (id, nombre, genero, estreno, idioma) VALUES (6, 'Inception', 'Accion, Sci-Fi', 2010, 'Ingles');
INSERT INTO peliculas (id, nombre, genero, estreno, idioma) VALUES (7, 'Matrix', 'Accion, Sci-Fi', 1999, 'Ingles');
INSERT INTO peliculas (id, nombre, genero, estreno, idioma) VALUES (8, 'Ciudad de Dios', 'Crimen, Drama', 2002, 'Portugues');
INSERT INTO peliculas (id, nombre, genero, estreno, idioma) VALUES (9, 'Gladiador', 'Accion, Drama', 2000, 'Ingles');
INSERT INTO peliculas (id, nombre, genero, estreno, idioma) VALUES (10, 'La Lista de Schindler', 'Biografia, Drama', 1993, 'Ingles');
